/*
 * Writes dist/boot.js: a stable name in front of the hashed bundle.
 *
 * GitHub Pages can be told to serve either the built site or the repository's
 * own files. When it serves the repository, index.html is the source template
 * and asks for src/main.tsx, which no browser can run — so the page is blank.
 *
 * The template falls back to this file when that happens. It needs a name that
 * does not change, because the template is checked in and the bundle's name is
 * a content hash that moves with every build. So the hashes are read out of the
 * built index.html here and baked into a file whose name is fixed.
 *
 * Paths are resolved from two different places and that is deliberate: a
 * dynamic import resolves against this module, which lives in dist/, while the
 * stylesheet href resolves against the document, which is a directory above.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const DIST = new URL('../dist/', import.meta.url).pathname;
const html = await readFile(join(DIST, 'index.html'), 'utf8');

const script = html.match(/src="\.\/(assets\/[^"]+\.js)"/)?.[1];
const style = html.match(/href="\.\/(assets\/[^"]+\.css)"/)?.[1];
if (!script) throw new Error('no bundle found in dist/index.html');

await writeFile(
  join(DIST, 'boot.js'),
  `// Generated by scripts/write-boot.mjs. Do not edit.\n` +
    (style
      ? `document.head.insertAdjacentHTML(\n` +
        `  'beforeend',\n` +
        `  '<link rel="stylesheet" href="./dist/${style}">',\n` +
        `);\n`
      : '') +
    `import('./${script}');\n`,
  'utf8',
);

console.log(`boot.js -> ${script}${style ? ' + ' + style : ''}`);
